pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }
        
        stage('Setup Environment') {
            steps {
                sh '''
                cd files && \
                python3 -m venv venv && \
                . venv/bin/activate && \
                pip install -r requirements.txt
                '''
            }
        }

        stage('Lint Code') {
            steps {
                sh '''
                cd files && \
                . venv/bin/activate && \
                flake8 app.py test.py
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                cd files && \
                . venv/bin/activate && \
                pytest test.py --junitxml=test-results.xml
                '''
            }
        }
    }
    
    post {
        always {
            // We also need to tell the JUnit plugin where to find the results
            junit 'files/test-results.xml'
        }
    }
}